### ISSUE TITLE
Is there any way or plan to make class overridable?

### ISSUE THREAD

**Issue by peinan** [moskomule/chika#7]
Hello, I'm trying to use chika to manage configurations in my experiments and came out with an idea to make it more useful.
The usage I'm thinking about is as below:

```python
@chika.config
class DefaultParamConfig:
  MAX_SEQ_LEN: int = 100
  NUM_EPOCH: int = 10

@chika.config
class ModelAParamConfig(DefaultParamConfig):
  MAX_SEQ_LEN: int = 150
  BATCH_SIZE: int = 32

@chika.main(ModelAParamConfig)
def main(cfg: ModelAParamConfig):
  print(cfg.MAX_SEQ_LEN)  # it will be 150
  print(cfg.NUM_EPOCH)  # I want it be 10 but it will raise AttributeError now
```

I think this can make configuration management more structured, like one default setting, and many experimental settings.

```
config/
- default.py
- model_a.py
- model_b.py
```

This idea is inspired by [OmegaConf](https://github.com/omry/omegaconf), which can make configurations stacked with the `merge()` method. But I think it will be more cool and simple to use class inheritance as shown above. Please give it some consideration.

![image](https://user-images.githubusercontent.com/5601012/95823487-aa4f0f80-0d68-11eb-9a64-3a7e416b5c9b.png)

**Comment by moskomule** [comment]
Thank you for a feature request. 
Actually, `dataclass`, the backend of `chika.config` is a bit complicated. 
I think this request will definitely improve chika, so I'll consider how to implement it in easy APIs.

**Comment by moskomule** [comment]
Hi, #8 resolved this issue.
